# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# ruby File.read('.ruby-version')
ruby '3.2.2'

gem 'activeadmin', '~> 2.14'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'devise', '~> 4.9.2'
gem 'draper', '~> 4.0', '>= 4.0.2'
gem 'image_processing', '~> 1.12', '>= 1.12.2'
gem 'jsonapi-serializer', '~> 2.2'
gem 'jwt_sessions', '~> 3.1.1'
gem 'pagy', '~> 6.0', '>= 6.0.4'
gem 'pg', '~> 1.1'
gem 'puma', '~> 6.4'
gem 'pundit', '~> 2.3'
gem 'rack-cors', '~> 2.0', '>= 2.0.1'
gem 'rails', '~> 7.0', '>= 7.0.7.1'
gem 'redis-client', '~> 0.16.0'
gem 'aws-sdk-s3', '~> 1.136'
gem 'geocoder', '~> 1.3', '>= 1.3.7'
gem 'rswag', '~> 2.11'
gem 'sass-rails', '~> 6.0.0'
gem 'seedbank', '~> 0.5.0'
gem 'sentry-rails', '~> 5.12.0'
gem 'sentry-ruby', '~> 5.12.0'
gem 'shrine', '~> 3.5'
gem 'sidekiq', '~> 7.1', '>= 7.1.6'
gem 'sprockets-rails', '~> 3.4.2'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test, :stage do
  gem 'bullet', '~> 7.0', '>= 7.0.7'
  gem 'bundler-audit', '~> 0.9.1'
  gem 'bundler-leak', '~> 0.3.0'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.2'
  gem 'ffaker', '~> 2.21'
  gem 'lefthook', '~> 1.4', '>= 1.4.1'
  gem 'letter_opener', '~> 1.8', '>= 1.8.1'
  gem 'pry-byebug'
  gem 'pry-rails', '~> 0.3.9'
  gem 'resolv', '~> 0.2.2'
  gem 'rspec-rails', '~> 6.0.0'
  gem 'rubocop', '~> 1.47', require: false
  gem 'rubocop-md', '~> 1.2', require: false
  gem 'rubocop-performance', '~> 1.16', require: false
  gem 'rubocop-rails', '~> 2.17', require: false
  gem 'rubocop-rake', '~> 0.6.0', require: false
  gem 'rubocop-rspec', '~> 2.22', require: false
  gem 'strong_migrations', '~> 1.4', '>= 1.4.4'
end

group :development do
  gem 'brakeman', '~> 5.4.1'
end

group :test do
  gem 'fakeredis', '~> 0.9.2', require: 'fakeredis/rspec'
  gem 'json_matchers', '~> 0.11.1'
  gem 'pundit-matchers', '~> 3.1'
  gem 'shoulda-matchers', '~> 5.3'
  gem 'simplecov', '~> 0.22.0', require: false
  gem 'timecop', '~> 0.9.6'
end
